### PR TITLE
fix(sensor): don't set `last_reset` for `total_increasing` sensor

### PR DESCRIPTION
**Pull request by folke**
Sensors in Home Assistant with device class `total_increasing` should not set `last_reset`.

```
2024-05-12 09:08:49.037 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1037, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
    if state_attributes := self.state_attributes:
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 446, in state_attributes
    raise ValueError(
ValueError: Entity sensor.heat_pump_house_partial_active_energy_delivered (<class 'custom_components.powertag_gateway.sensor.PowerTagPartialActiveEnergyDelivered'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured.
```

### CODE REVIEW

**Comment by folke** [comment]
Any chance this can get merged?

**Comment by Breina** [comment]
Sorry for leaving you hanging! This escaped my focus. :(

I'll merge, hold up

**Comment by Breina** [comment]
I'll release in a little bit, still a small thing I need to do for #15

**Comment by Breina** [comment]
Also, thanks a lot for the fix! :)

**Comment by folke** [comment]
ty!

**Comment by Breina** [comment]
Release: https://github.com/Breina/PowerTagGateway/releases/tag/v0.5.2

**Pull request merged**
